adjective1 = input("Tell me an adjective, and click enter. ")
noun1 = input("Tell me a noun (plural), and click enter. ")
noun2 = input("Tell me another noun, and click enter. ")
adjective2 = input("Tell me an another adjective, and click enter. ")
print ("\n")
print ("Roses are....and so are you!")
print("\n")
print ("Roses are " + adjective1)
print (noun1 + " are blue")
print (noun2 + " is " + adjective2)
print ("And so are you!")